export const projects = [
  {
    id: 'museum',
    image: '/museum.png',
    alt: 'A screenshot of the website for the museum called Community Science Museum',
    task: 'SEMESTER PROJECT 1',
    title: 'Community Science Museum, 1. Semester',
    githubLink: 'https://github.com/MartineMidttveit/Semester-Project-1.git',
    netlifyLink: 'https://superb-cuchufli-244246.netlify.app',
  },
  {
    id: 'gamehub',
    image: '/gamehub.png',
    alt: 'A screenshot of the website for an online store selling video games called GameHub',
    task: 'CROSS-COURSE PROJECT',
    title: 'GameHub, 1. Semester',
    githubLink: 'https://github.com/MartineMidttveit/GameHub3.git',
    netlifyLink: 'https://peaceful-kringle-7a8bfb.netlify.app/',
  },
  {
    id: 'holidaze',
    image: '/holidaze.png',
    alt: 'A screenshot of the website for an online bookings',
    task: 'Holidaze, 4. semester.',
    title: 'Project Exam 2.',
    githubLink: 'https://github.com/MartineMidttveit/Holidaze-Delivery',
    netlifyLink: 'https://magical-bubblegum-275196.netlify.app/',
  },
  {
    id: 'code-unity',
    image: '/code-unity.png',
    alt: 'A screenshot of the website for an online community of coders',
    task: 'CodeUnity, 3.semester',
    title: 'Collaboration project',
    githubLink: 'https://github.com/Krihag/CodeUnity/tree/JS2',
    netlifyLink: 'https://coruscating-semolina-42bdb7.netlify.app/',
  },
  {
    id: 'bidlify',
    image: '/bidlify.png',
    alt: 'A screenshot of the website for an online bid system',
    task: 'Bidlify, 3.semester',
    title: 'Semester Project 2',
    githubLink: 'https://github.com/MartineMidttveit/Bidlify-SP2 ',
    netlifyLink: 'https://bidlifyy.netlify.app/',
  },
];